[theme]
primaryColor = "#FFCCCC"  # Light red for the main app
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#87CEEB"  # Sky blue for the sidebar
textColor = "#000000"  # Black text color
font = "sans serif"  # Set font to sans serif

[fonts]
sans_serif = "Arial, Helvetica, sans-serif"

